spring:
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

  redis:
    host: 119.23.211.119  #服务器主机地址
    port: 6379  #端口：6379
    database: 0  #数据库：默认为0
    password: "P@ssword666"
    timeout: 0  #连接超时时间（毫秒）
    pool:
      max-active: 8  #连接池最大连接数
      max-wait: -1  #连接池最大阻塞等待时间
      max-idle: 8  #连接池中的最大空闲连接
      min-idle: 0  #连接池中的最小空闲连接
