server:
  context-path: "/MineMine"
  port: 8888
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: MineMine
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update

  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 119.23.211.119
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: "P@ssword666"
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

  mail:
    # 邮箱地址
    host: smtp.163.com
    # 用户名和授权码
    username: lieh_666@163.com
    password: Xiao163He00
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
